using Microsoft.EntityFrameworkCore;
using Oriental_Oasis_Web.Models;

namespace Oriental_Oasis_Web.Data
{
    //config for entity Framework core
    public class ApplicationDbContext : DbContext
    {
        //constructor for the class and config the DbContentOptions for the class and the options wiill be passed to the class DbContext
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> option) : base(option)
        {
            
        }
        //create database set for the table, then go to Tools-NuGet Manager Console and type 'add-migration AddCategoryTableToDb'.
        //This will create another file if there is a primary key defined in Category.cs and use data annotation [key]
        public DbSet <Category>Categories { get; set; }

        //override the default func that generated by the model.( ModelBuilder is default by the entiry framework)
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //override the default behavior by create entity objects which defined in Category.cs.
            //this tells the Entiry Framework to create these records
            modelBuilder.Entity<Category>().HasData(
                new Category { Cat_Id = 1, Name = "Ceramics", DisplayOrder = 1 },
                new Category { Cat_Id = 2, Name = "Ceramics", DisplayOrder = 2 },
                new Category { Cat_Id = 3, Name = "Ceramics", DisplayOrder = 3 }

                );
        }
    }
}
